<?php
/**
 * @file
 * Code for the GSB Feature Publication Display feature.
 */

include_once 'gsb_feature_publication_display.features.inc';

/**
 * Implementation of hook_module_implements_alter()
 */
function gsb_feature_publication_display_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['gsb_feature_publication_display'])) {
      $group = $implementations['gsb_feature_publication_display'];
      unset($implementations['gsb_feature_publication_display']);
      $implementations['gsb_feature_publication_display'] = $group;
    }
  }
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_publication_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {
  // Alter 'Publication filters' content pane settings form.

  if ($form_state['pane']->subtype == 'publication_filters-panel_pane_1' && $form_state['view']->name == 'publication_filters' && $form_state['view']->current_display == 'panel_pane_1') {
   //Hide all display modes except compact and expanded

    $view_modes = $form['view_mode']['#options'];
    foreach($view_modes as $key=>$value) {
      if($key !== 'compact' AND $key !== 'expanded'){
        unset($form['view_mode']['#options'][$key]);
      }
    }

    $form['exposed']['widget_title']['#field_prefix'] = 'Block Title';
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['filter-field_person_fac_single_ref_target_id']['#description'] = 'Enter faculty node ID.';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['arguments']['#access'] = FALSE;
    //$form['exposed']['filter-title']['#weight'] = -99;
    $form['exposed']['arguments']['#weight'] = 90;
    $form['context']['#access'] = FALSE;
    $form['comments']['#access'] = FALSE;
    $form['links']['#access'] = FALSE;
    $conf = $form_state['conf'];
    $item['title_link'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
      '#weight' => -99,
      '#default_value' => !empty($conf['title_link']) ? $conf['title_link'] : '',
    );
    $form['override_title']['#weight'] = -99;
    $form['items_per_page']['#weight'] = -99;
    $form['view_mode']['#weight'] = -99;
    $form['exposed']['#weight'] = -98;

    $form = gsb_misc_fixes_associative_insert($form, 'override_title_text', $item);
    $form['#validate'][] = 'gsb_feature_publication_display_form_validate';
    $form['#submit'][] = 'gsb_feature_publication_display_form_submit';
  }
}

function gsb_feature_publication_display_form_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save title link field in pane config.
 */
function gsb_feature_publication_display_form_submit($form, &$form_state) {
  $form_state['conf']['title_link'] = $form_state['values']['title_link'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter 'Publication Filter' content pane title to be linked to a custom URL.
 */
function gsb_feature_publication_display_panels_pane_content_alter($content, $pane, $args, $context) {
  //dpm($content);
  if ($content && $content->subtype == 'publication_filters-panel_pane_1') {
    if (!empty($pane->configuration['title_link'])) {
      $content->title = decode_entities(l($content->title, $pane->configuration['title_link']));
    }
  }

}
//function HOOK_panels_pane_content_alter($content, $pane, $args, $context) {
//  if ($content->title) {
//    $content->title = t($content->title);
//  }
//  return $content;
//}
