<?php
/**
 * @file
 * Code for the GSB Feature Publication Display feature.
 */

include_once 'gsb_feature_publication_display.features.inc';

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function gsb_feature_publication_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'publication_filters') {
    // Exclude the search text field from auto-submit.
    $form['search']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
  }
}
